---
repos:
  # See https://pre-commit.com for more information
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: check-merge-conflict
    - id: check-case-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    - id: remove-crlf
    - id: remove-tabs

  - repo: https://github.com/norwoodj/helm-docs.git
    rev: v1.13.1
    hooks:
     - id: helm-docs
       args:
         # Make the tool search for charts only under the `charts` directory
         - --chart-search-root=charts
