{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-db-cm
  labels: {{- include "unifi-network-app.labels" . | nindent 4 }}
data:
  init-mongo.js: |-
    db.getSiblingDB("{{ .Values.unifi.db.name }}").createUser({user: "{{ .Values.unifi.db.user }}", pwd: "{{ .Values.unifi.db.password }}", roles: [{role: "dbOwner", db: "{{ .Values.unifi.db.name }}"}]});
    db.getSiblingDB("{{ .Values.unifi.db.name }}_stat").createUser({user: "{{ .Values.unifi.db.user }}", pwd: "{{ .Values.unifi.db.password }}", roles: [{role: "dbOwner", db: "{{ .Values.unifi.db.name }}_stat"}]});
{{- end }}