{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "unifi-network-app.fullname" . }}-mongodb-cm"
  labels: {{- include "unifi-network-app.labels" . | nindent 4 }}
data:
  init-mongo.js: |-
    db.getSiblingDB("{{ .Values.mongodb.db_name }}").createUser({user: "{{ .Values.mongodb.db_user }}", pwd: "{{ .Values.mongodb.db_password }}", roles: [{role: "dbOwner", db: "{{ .Values.mongodb.db_name }}"}]});
    db.getSiblingDB("{{ .Values.mongodb.db_name }}_stat").createUser({user: "{{ .Values.mongodb.db_user }}", pwd: "{{ .Values.mongodb.db_password }}", roles: [{role: "dbOwner", db: "{{ .Values.mongodb.db_name }}_stat"}]});
{{- end }}